<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PopulateCostCenters extends Seeder
{
    public function run(): void
    {
        $costCenters = [
            // --- 1
            ['name' => 'Lab. Sólidos', 'company_id' => 1],
            ['name' => 'Material Aplicado', 'company_id' => 1],
            ['name' => 'Revenda', 'company_id' => 1],
            ['name' => 'Lab. Injetáveis', 'company_id' => 1],
            ['name' => 'Lab. Hormônios', 'company_id' => 1],
            ['name' => 'Lab. Líquidos', 'company_id' => 1],
            ['name' => 'Almoxarifado', 'company_id' => 1],
            ['name' => 'Conferência de entrada', 'company_id' => 1],
            ['name' => 'Conferência de Saída', 'company_id' => 1],
            ['name' => 'Diretoria de Produção', 'company_id' => 1],
            ['name' => 'Inclusão', 'company_id' => 1],
            ['name' => 'Limpeza', 'company_id' => 1],
            ['name' => 'Manutenção', 'company_id' => 1],
            ['name' => 'Qualidade', 'company_id' => 1],
            ['name' => 'Segurança do Trabalho', 'company_id' => 1],
            ['name' => 'Noorskin', 'company_id' => 1],
            ['name' => 'Receitas para Vendas', 'company_id' => 1],
            ['name' => 'Tele Atendimento', 'company_id' => 1],
            ['name' => 'Congressos e Eventos', 'company_id' => 1],
            ['name' => 'Diretoria Vendas e Marketing', 'company_id' => 1],
            ['name' => 'Expedição', 'company_id' => 1],
            ['name' => 'Faturamento/Caixa', 'company_id' => 1],
            ['name' => 'Marketing', 'company_id' => 1],
            ['name' => 'Recepção', 'company_id' => 1],
            ['name' => 'Visitação', 'company_id' => 1],
            ['name' => 'Comercial Injetáveis', 'company_id' => 1],
            ['name' => 'Diretoria Visitação', 'company_id' => 1],
            ['name' => 'Administrativo(setor terro HKM)', 'company_id' => 1],
            ['name' => 'Diretoria Administrativo', 'company_id' => 1],
            ['name' => 'Suprimentos', 'company_id' => 1],
            ['name' => 'Diretoria', 'company_id' => 1],
            ['name' => 'Infraestrutura e Telecom', 'company_id' => 1],
            ['name' => 'Diretoria de Tecnologia', 'company_id' => 1],
            ['name' => 'T.I Technologies', 'company_id' => 1],
            ['name' => 'Software e Sistemas', 'company_id' => 1],
            ['name' => 'Inteligência de Negócio', 'company_id' => 1],
            ['name' => 'Digital', 'company_id' => 1],
            ['name' => 'ERP', 'company_id' => 1],
            ['name' => 'DDH', 'company_id' => 1],
            ['name' => 'Diretoria DDH', 'company_id' => 1],
            ['name' => 'Recursos Humanos', 'company_id' => 1],
            ['name' => 'Departamento Pessoal', 'company_id' => 1],
            ['name' => 'Endomarketing', 'company_id' => 1],
            ['name' => 'Financeiro', 'company_id' => 1],
            ['name' => 'Diretoria financeira', 'company_id' => 1],
            ['name' => 'Tritutário', 'company_id' => 1],
            ['name' => 'Controladoria', 'company_id' => 1],
            ['name' => 'P&d', 'company_id' => 1],
            // --- 2
            ['name' => 'Material Aplicado', 'company_id' => 2],
            ['name' => 'Lab Injetáveis', 'company_id' => 2],
            ['name' => 'Revenda', 'company_id' => 2],
            ['name' => 'Lab. Hormônios', 'company_id' => 2],
            ['name' => 'Lab. Líquidos', 'company_id' => 2],
            ['name' => 'Lab. Sólidos', 'company_id' => 2],
            ['name' => 'Conferência de Entrada', 'company_id' => 2],
            ['name' => 'Conferência de Saída', 'company_id' => 2],
            ['name' => 'Diretoria de Produção', 'company_id' => 2],
            ['name' => 'Inclusão', 'company_id' => 2],
            ['name' => 'Limpeza', 'company_id' => 2],
            ['name' => 'Manutenção', 'company_id' => 2],
            ['name' => 'Qualidade', 'company_id' => 2],
            ['name' => 'Segurança do Trabalho', 'company_id' => 2],
            ['name' => 'Almoxarifado', 'company_id' => 2],
            ['name' => 'Noorskin', 'company_id' => 2],
            ['name' => 'Receita para vendas', 'company_id' => 2],
            ['name' => 'Atendimento', 'company_id' => 2],
            ['name' => 'Congressos e Eventos', 'company_id' => 2],
            ['name' => 'Diretoria Vendas e Marketing', 'company_id' => 2],
            ['name' => 'Expedição', 'company_id' => 2],
            ['name' => 'Faturamento/Caixa', 'company_id' => 2],
            ['name' => 'Marketing', 'company_id' => 2],
            ['name' => 'Visitação', 'company_id' => 2],
            ['name' => 'Tele Atendimento', 'company_id' => 2],
            ['name' => 'Administrativo', 'company_id' => 2],
            ['name' => 'Diretoria Administrativo', 'company_id' => 2],
            ['name' => 'Suprimentos', 'company_id' => 2],
            ['name' => 'Diretoria', 'company_id' => 2],
            ['name' => 'Infraestrutura e Telecom', 'company_id' => 2],
            ['name' => 'Software e Sistemas', 'company_id' => 2],
            ['name' => 'Inteligência de Negócio', 'company_id' => 2],
            ['name' => 'TI Technologies', 'company_id' => 2],
            ['name' => 'Digital', 'company_id' => 2],
            ['name' => 'ERP', 'company_id' => 2],
            ['name' => 'DDH', 'company_id' => 2],
            ['name' => 'Recursos Humanos', 'company_id' => 2],
            ['name' => 'Departamento Pessoal', 'company_id' => 2],
            ['name' => 'Financeiro', 'company_id' => 2],
            ['name' => 'Diretoria Financeira', 'company_id' => 2],
            ['name' => 'Tributario', 'company_id' => 2],
            ['name' => 'Controladoria', 'company_id' => 2],
            ['name' => 'P&d', 'company_id' => 2],
            //--- 3
            ['name' => 'Material Aplicado', 'company_id' => 3],
            ['name' => 'Lab Injetáveis', 'company_id' => 3],
            ['name' => 'Revenda', 'company_id' => 3],
            ['name' => 'Lab. Hormônios', 'company_id' => 3],
            ['name' => 'Lab. Líquidos', 'company_id' => 3],
            ['name' => 'Lab. Sólidos', 'company_id' => 3],
            ['name' => 'Conferência de Entrada', 'company_id' => 3],
            ['name' => 'Conferência de Saída', 'company_id' => 3],
            ['name' => 'Diretoria de Produção', 'company_id' => 3],
            ['name' => 'Inclusão', 'company_id' => 3],
            ['name' => 'Limpeza', 'company_id' => 3],
            ['name' => 'Manutenção', 'company_id' => 3],
            ['name' => 'Qualidade', 'company_id' => 3],
            ['name' => 'Segurança do Trabalho', 'company_id' => 3],
            ['name' => 'Almoxarifado', 'company_id' => 3],
            ['name' => 'Noorskin', 'company_id' => 3],
            ['name' => 'Receita para vendas', 'company_id' => 3],
            ['name' => 'Atendimento', 'company_id' => 3],
            ['name' => 'Congressos e Eventos', 'company_id' => 3],
            ['name' => 'Diretoria Vendas e Marketing', 'company_id' => 3],
            ['name' => 'Expedição', 'company_id' => 3],
            ['name' => 'Faturamento/Caixa', 'company_id' => 3],
            ['name' => 'Marketing', 'company_id' => 3],
            ['name' => 'Visitação', 'company_id' => 3],
            ['name' => 'Tele Atendimento', 'company_id' => 3],
            ['name' => 'Administrativo', 'company_id' => 3],
            ['name' => 'Diretoria Administrativo', 'company_id' => 3],
            ['name' => 'Suprimentos', 'company_id' => 3],
            ['name' => 'Diretoria', 'company_id' => 3],
            ['name' => 'Infraestrutura e Telecom', 'company_id' => 3],
            ['name' => 'Software e Sistemas', 'company_id' => 3],
            ['name' => 'Inteligência de Negócio', 'company_id' => 3],
            ['name' => 'TI Technologies', 'company_id' => 3],
            ['name' => 'Digital', 'company_id' => 3],
            ['name' => 'ERP', 'company_id' => 3],
            ['name' => 'DDH', 'company_id' => 3],
            ['name' => 'Recursos Humanos', 'company_id' => 3],
            ['name' => 'Departamento Pessoal', 'company_id' => 3],
            ['name' => 'Financeiro', 'company_id' => 3],
            ['name' => 'Diretoria Financeira', 'company_id' => 3],
            ['name' => 'Tributario', 'company_id' => 3],
            ['name' => 'Controladoria', 'company_id' => 3],
            ['name' => 'P&d', 'company_id' => 3],
            // --- 4
            ['name' => 'Material Aplicado', 'company_id' => 4],
            ['name' => 'Lab Injetáveis', 'company_id' => 4],
            ['name' => 'Revenda', 'company_id' => 4],
            ['name' => 'Lab. Hormônios', 'company_id' => 4],
            ['name' => 'Lab. Líquidos', 'company_id' => 4],
            ['name' => 'Lab. Sólidos', 'company_id' => 4],
            ['name' => 'Conferência de Entrada', 'company_id' => 4],
            ['name' => 'Conferência de Saída', 'company_id' => 4],
            ['name' => 'Diretoria de Produção', 'company_id' => 4],
            ['name' => 'Inclusão', 'company_id' => 4],
            ['name' => 'Limpeza', 'company_id' => 4],
            ['name' => 'Manutenção', 'company_id' => 4],
            ['name' => 'Qualidade', 'company_id' => 4],
            ['name' => 'Segurança do Trabalho', 'company_id' => 4],
            ['name' => 'Almoxarifado', 'company_id' => 4],
            ['name' => 'Noorskin', 'company_id' => 4],
            ['name' => 'Receita para vendas', 'company_id' => 4],
            ['name' => 'Atendimento', 'company_id' => 4],
            ['name' => 'Congressos e Eventos', 'company_id' => 4],
            ['name' => 'Diretoria Vendas e Marketing', 'company_id' => 4],
            ['name' => 'Expedição', 'company_id' => 4],
            ['name' => 'Faturamento/Caixa', 'company_id' => 4],
            ['name' => 'Marketing', 'company_id' => 4],
            ['name' => 'Visitação', 'company_id' => 4],
            ['name' => 'Tele Atendimento', 'company_id' => 4],
            ['name' => 'Administrativo', 'company_id' => 4],
            ['name' => 'Diretoria Administrativo', 'company_id' => 4],
            ['name' => 'Suprimentos', 'company_id' => 4],
            ['name' => 'Diretoria', 'company_id' => 4],
            ['name' => 'Infraestrutura e Telecom', 'company_id' => 4],
            ['name' => 'Software e Sistemas', 'company_id' => 4],
            ['name' => 'Inteligência de Negócio', 'company_id' => 4],
            ['name' => 'TI Technologies', 'company_id' => 4],
            ['name' => 'Digital', 'company_id' => 4],
            ['name' => 'ERP', 'company_id' => 4],
            ['name' => 'DDH', 'company_id' => 4],
            ['name' => 'Recursos Humanos', 'company_id' => 4],
            ['name' => 'Departamento Pessoal', 'company_id' => 4],
            ['name' => 'Financeiro', 'company_id' => 4],
            ['name' => 'Diretoria Financeira', 'company_id' => 4],
            ['name' => 'Tributario', 'company_id' => 4],
            ['name' => 'Controladoria', 'company_id' => 4],
            ['name' => 'P&d', 'company_id' => 4],
            // --- 5
            ['name' => 'Revenda', 'company_id' => 5],
            ['name' => 'Almoxarifado', 'company_id' => 5],
            ['name' => 'Limpeza (produção)', 'company_id' => 5],
            ['name' => 'Manutenção (produção)', 'company_id' => 5],
            ['name' => 'Qualidade', 'company_id' => 5],
            ['name' => 'Segurança do Trabalho', 'company_id' => 5],
            ['name' => 'Noorskin', 'company_id' => 5],
            ['name' => 'Receitas para Vendas', 'company_id' => 5],
            ['name' => 'Atendimento E-Commerce e SAC', 'company_id' => 5],
            ['name' => 'Congressos e Eventos', 'company_id' => 5],
            ['name' => 'Diretoria Vendas e Marketing', 'company_id' => 5],
            ['name' => 'Expedição', 'company_id' => 5],
            ['name' => 'Faturamento', 'company_id' => 5],
            ['name' => 'Marketing', 'company_id' => 5],
            ['name' => 'Recepção', 'company_id' => 5],
            ['name' => 'Visitação', 'company_id' => 5],
            ['name' => 'Diretoria Administrativo', 'company_id' => 5],
            ['name' => 'Suprimentos', 'company_id' => 5],
            ['name' => 'Novos Projetos', 'company_id' => 5],
            ['name' => 'Diretoria', 'company_id' => 5],
            ['name' => 'Infraestrutura e Telecom', 'company_id' => 5],
            ['name' => 'TI Technologies', 'company_id' => 5],
            ['name' => 'DDH', 'company_id' => 5],
            ['name' => 'Financeiro', 'company_id' => 5],
            ['name' => 'Diretoria financeira', 'company_id' => 5],
            ['name' => 'Tributário', 'company_id' => 5],
            ['name' => 'Controladoria', 'company_id' => 5],
            // --- 6
            ['name' => 'Revenda', 'company_id' => 6],
            ['name' => 'Almoxarifado', 'company_id' => 6],
            ['name' => 'Limpeza', 'company_id' => 6],
            ['name' => 'Manutenção', 'company_id' => 6],
            ['name' => 'Qualidade', 'company_id' => 6],
            ['name' => 'Segurança do Trabalho', 'company_id' => 6],
            ['name' => 'Receitas para Vendas', 'company_id' => 6],
            ['name' => 'Atendimento E-Commerce e SAC', 'company_id' => 6],
            ['name' => 'Congressos e Eventos', 'company_id' => 6],
            ['name' => 'Diretoria Vendas e Marketing', 'company_id' => 6],
            ['name' => 'Expedição', 'company_id' => 6],
            ['name' => 'Faturamento', 'company_id' => 6],
            ['name' => 'Marketing', 'company_id' => 6],
            ['name' => 'Recepção', 'company_id' => 6],
            ['name' => 'Visitação', 'company_id' => 6],
            ['name' => 'Contabilidade', 'company_id' => 6],
            ['name' => 'DDH', 'company_id' => 6],
            ['name' => 'Diretoria Administrativo/Financeiro', 'company_id' => 6],
            ['name' => 'Financeiro', 'company_id' => 6],
            ['name' => 'Suprimentos', 'company_id' => 6],
            ['name' => 'TI', 'company_id' => 6],
            // --- 7
            ['name' => 'Revenda', 'company_id' => 7],
            ['name' => 'Almoxarifado', 'company_id' => 7],
            ['name' => 'Limpeza (produção)', 'company_id' => 7],
            ['name' => 'Manutenção (produção)', 'company_id' => 7],
            ['name' => 'Qualidade', 'company_id' => 7],
            ['name' => 'Segurança do Trabalho', 'company_id' => 7],
            ['name' => 'Noorskin', 'company_id' => 7],
            ['name' => 'Receitas para Vendas', 'company_id' => 7],
            ['name' => 'Atendimento E-Commerce e SAC', 'company_id' => 7],
            ['name' => 'Congressos e Eventos', 'company_id' => 7],
            ['name' => 'Diretoria Vendas e Marketing', 'company_id' => 7],
            ['name' => 'Expedição', 'company_id' => 7],
            ['name' => 'Faturamento', 'company_id' => 7],
            ['name' => 'Marketing', 'company_id' => 7],
            ['name' => 'Recepção', 'company_id' => 7],
            ['name' => 'Visitação', 'company_id' => 7],
            ['name' => 'Diretoria Administrativo', 'company_id' => 7],
            ['name' => 'Suprimentos', 'company_id' => 7],
            ['name' => 'Novos Projetos', 'company_id' => 7],
            ['name' => 'Diretoria', 'company_id' => 7],
            ['name' => 'Infraestrutura e Telecom', 'company_id' => 7],
            ['name' => 'TI Technologies', 'company_id' => 7],
            ['name' => 'DDH', 'company_id' => 7],
            ['name' => 'Financeiro', 'company_id' => 7],
            ['name' => 'Diretoria financeira', 'company_id' => 7],
            ['name' => 'Tributário', 'company_id' => 7],
            ['name' => 'Controladoria', 'company_id' => 7],
            // --- 8
            ['name' => 'Revenda', 'company_id' => 8],
            ['name' => 'Almoxarifado', 'company_id' => 8],
            ['name' => 'Limpeza (produção)', 'company_id' => 8],
            ['name' => 'Manutenção (produção)', 'company_id' => 8],
            ['name' => 'Qualidade', 'company_id' => 8],
            ['name' => 'Segurança do Trabalho', 'company_id' => 8],
            ['name' => 'Noorskin', 'company_id' => 8],
            ['name' => 'Receitas para Vendas', 'company_id' => 8],
            ['name' => 'Atendimento E-Commerce e SAC', 'company_id' => 8],
            ['name' => 'Congressos e Eventos', 'company_id' => 8],
            ['name' => 'Diretoria Vendas e Marketing', 'company_id' => 8],
            ['name' => 'Expedição', 'company_id' => 8],
            ['name' => 'Faturamento', 'company_id' => 8],
            ['name' => 'Marketing', 'company_id' => 8],
            ['name' => 'Recepção', 'company_id' => 8],
            ['name' => 'Visitação', 'company_id' => 8],
            ['name' => 'Diretoria Administrativo', 'company_id' => 8],
            ['name' => 'Suprimentos', 'company_id' => 8],
            ['name' => 'Novos Projetos', 'company_id' => 8],
            ['name' => 'Diretoria', 'company_id' => 8],
            ['name' => 'Infraestrutura e Telecom', 'company_id' => 8],
            ['name' => 'TI Technologies', 'company_id' => 8],
            ['name' => 'DDH', 'company_id' => 8],
            ['name' => 'Financeiro', 'company_id' => 8],
            ['name' => 'Diretoria financeira', 'company_id' => 8],
            ['name' => 'Tributário', 'company_id' => 8],
            ['name' => 'Controladoria', 'company_id' => 8],
            // --- 9
            ['name' => 'Revenda', 'company_id' => 9],
            ['name' => 'Almoxarifado', 'company_id' => 9],
            ['name' => 'Limpeza (produção)', 'company_id' => 9],
            ['name' => 'Manutenção (produção)', 'company_id' => 9],
            ['name' => 'Qualidade', 'company_id' => 9],
            ['name' => 'Segurança do Trabalho', 'company_id' => 9],
            ['name' => 'Noorskin', 'company_id' => 9],
            ['name' => 'Receitas para Vendas', 'company_id' => 9],
            ['name' => 'Atendimento E-Commerce e SAC', 'company_id' => 9],
            ['name' => 'Congressos e Eventos', 'company_id' => 9],
            ['name' => 'Diretoria Vendas e Marketing', 'company_id' => 9],
            ['name' => 'Expedição', 'company_id' => 9],
            ['name' => 'Faturamento', 'company_id' => 9],
            ['name' => 'Marketing', 'company_id' => 9],
            ['name' => 'Recepção', 'company_id' => 9],
            ['name' => 'Visitação', 'company_id' => 9],
            ['name' => 'Diretoria Administrativo', 'company_id' => 9],
            ['name' => 'Suprimentos', 'company_id' => 9],
            ['name' => 'Novos Projetos', 'company_id' => 9],
            ['name' => 'Diretoria', 'company_id' => 9],
            ['name' => 'Infraestrutura e Telecom', 'company_id' => 9],
            ['name' => 'TI Technologies', 'company_id' => 9],
            ['name' => 'DDH', 'company_id' => 9],
            ['name' => 'Financeiro', 'company_id' => 9],
            ['name' => 'Diretoria financeira', 'company_id' => 9],
            ['name' => 'Tributário', 'company_id' => 9],
            ['name' => 'Controladoria', 'company_id' => 9],
            // --- 10
            ['name' => 'Revenda', 'company_id' => 10],
            ['name' => 'Almoxarifado', 'company_id' => 10],
            ['name' => 'Limpeza (produção)', 'company_id' => 10],
            ['name' => 'Manutenção (produção)', 'company_id' => 10],
            ['name' => 'Qualidade', 'company_id' => 10],
            ['name' => 'Segurança do Trabalho', 'company_id' => 10],
            ['name' => 'Noorskin', 'company_id' => 10],
            ['name' => 'Receitas para Vendas', 'company_id' => 10],
            ['name' => 'Atendimento E-Commerce e SAC', 'company_id' => 10],
            ['name' => 'Congressos e Eventos', 'company_id' => 10],
            ['name' => 'Diretoria Vendas e Marketing', 'company_id' => 10],
            ['name' => 'Expedição', 'company_id' => 10],
            ['name' => 'Faturamento', 'company_id' => 10],
            ['name' => 'Marketing', 'company_id' => 10],
            ['name' => 'Recepção', 'company_id' => 10],
            ['name' => 'Visitação', 'company_id' => 10],
            ['name' => 'Diretoria Administrativo', 'company_id' => 10],
            ['name' => 'Suprimentos', 'company_id' => 10],
            ['name' => 'Novos Projetos', 'company_id' => 10],
            ['name' => 'Diretoria', 'company_id' => 10],
            ['name' => 'Infraestrutura e Telecom', 'company_id' => 10],
            ['name' => 'TI Technologies', 'company_id' => 10],
            ['name' => 'DDH', 'company_id' => 10],
            ['name' => 'Financeiro', 'company_id' => 10],
            ['name' => 'Diretoria financeira', 'company_id' => 10],
            ['name' => 'Tributário', 'company_id' => 10],
            ['name' => 'Controladoria', 'company_id' => 10],
            // --- 11
            ['name' => 'Produção - Pesagem/Mistura', 'company_id' => 11],
            ['name' => 'Produção - Moinho', 'company_id' => 11],
            ['name' => 'Produção - Envase/Rotulagem', 'company_id' => 11],
            ['name' => 'Produção - Encartuchamento', 'company_id' => 11],
            ['name' => 'Produção - Ensacadora', 'company_id' => 11],
            ['name' => 'Diretoria tributário/Central de notas', 'company_id' => 11],
            ['name' => 'Controladoria', 'company_id' => 11],
            ['name' => 'Diretoria Controladoria', 'company_id' => 11],
            ['name' => 'Central de Notas', 'company_id' => 11],
            ['name' => 'Diretoria P&D', 'company_id' => 11],
            ['name' => 'Almoxarifado E-Commerce', 'company_id' => 11],
            ['name' => 'Atendimento E-Commerce e SAC', 'company_id' => 11],
            ['name' => 'Expedição E-Commerce', 'company_id' => 11],
            ['name' => 'Faturamento E-Commerce', 'company_id' => 11],
            ['name' => 'E-commerce Marketing', 'company_id' => 11],
            ['name' => 'Diretoria de Produção', 'company_id' => 11],
            ['name' => 'PCP (Planejamento de Produção)', 'company_id' => 11],
            ['name' => 'Almoxarifado', 'company_id' => 11],
            ['name' => 'Qualidade', 'company_id' => 11],
            ['name' => 'Manutenção', 'company_id' => 11],
            ['name' => 'Segurança do Trabalho', 'company_id' => 11],
            ['name' => 'Limpeza', 'company_id' => 11],
            ['name' => 'Noorskin', 'company_id' => 11],
            ['name' => 'Diretoria Vendas e Marketing', 'company_id' => 11],
            ['name' => 'Visitação', 'company_id' => 11],
            ['name' => 'Trade Marketing', 'company_id' => 11],
            ['name' => 'EAD', 'company_id' => 11],
            ['name' => 'Internacional', 'company_id' => 11],
            ['name' => 'SAC', 'company_id' => 11],
            ['name' => 'Congressos e Eventos', 'company_id' => 11],
            ['name' => 'Diretoria Visitação', 'company_id' => 11],
            ['name' => 'Marketing', 'company_id' => 11],
            ['name' => 'Vendas', 'company_id' => 11],
            ['name' => 'Faturamento', 'company_id' => 11],
            ['name' => 'Expedição', 'company_id' => 11],
            ['name' => 'Atendimento Site', 'company_id' => 11],
            ['name' => 'Diretoria Administrativo', 'company_id' => 11],
            ['name' => 'Novos Negócios', 'company_id' => 11],
            ['name' => 'Suprimentos', 'company_id' => 11],
            ['name' => 'Administrativo', 'company_id' => 11],
            ['name' => 'Arquitetura', 'company_id' => 11],
            ['name' => 'Diretoria', 'company_id' => 11],
            ['name' => 'Be Generous ', 'company_id' => 11],
            ['name' => 'Diretoria de Tecnologia', 'company_id' => 11],
            ['name' => 'Software e Sistemas', 'company_id' => 11],
            ['name' => 'Inteligência de Negócio', 'company_id' => 11],
            ['name' => 'Technologies', 'company_id' => 11],
            ['name' => 'Digital', 'company_id' => 11],
            ['name' => 'Infraestrutura e Telecom', 'company_id' => 11],
            ['name' => 'ERP', 'company_id' => 11],
            ['name' => 'Diretoria DDH', 'company_id' => 11],
            ['name' => 'DDH', 'company_id' => 11],
            ['name' => 'Recursos Humanos', 'company_id' => 11],
            ['name' => 'Departamento Pessoal', 'company_id' => 11],
            ['name' => 'Endomarketing', 'company_id' => 11],
            ['name' => 'Diretoria Financeiro', 'company_id' => 11],
            ['name' => 'Financeiro', 'company_id' => 11],
            ['name' => 'Tributário', 'company_id' => 11],
            ['name' => 'P&D', 'company_id' => 11],
            // --- 12
            ['name' => 'Diretoria tributário/Central de notas', 'company_id' => 12],
            ['name' => 'Controladoria', 'company_id' => 12],
            ['name' => 'Diretoria Controladoria', 'company_id' => 12],
            ['name' => 'Central de Notas', 'company_id' => 12],
            ['name' => 'Diretoria P&D', 'company_id' => 12],
            ['name' => 'Almoxarifado E-Commerce', 'company_id' => 12],
            ['name' => 'Atendimento E-Commerce e SAC', 'company_id' => 12],
            ['name' => 'Expedição E-Commerce', 'company_id' => 12],
            ['name' => 'Faturamento E-Commerce', 'company_id' => 12],
            ['name' => 'E-commerce Marketing', 'company_id' => 12],
            ['name' => 'Diretoria de Produção', 'company_id' => 12],
            ['name' => 'PCP (Planejamento de Produção)', 'company_id' => 12],
            ['name' => 'Almoxarifado', 'company_id' => 12],
            ['name' => 'Qualidade', 'company_id' => 12],
            ['name' => 'Manutenção', 'company_id' => 12],
            ['name' => 'Segurança do Trabalho', 'company_id' => 12],
            ['name' => 'Noorskin', 'company_id' => 12],
            ['name' => 'Diretoria Vendas e Marketing', 'company_id' => 12],
            ['name' => 'Visitação', 'company_id' => 12],
            ['name' => 'Trade Marketing', 'company_id' => 12],
            ['name' => 'EAD', 'company_id' => 12],
            ['name' => 'Internacional', 'company_id' => 12],
            ['name' => 'SAC', 'company_id' => 12],
            ['name' => 'Congressos e Eventos', 'company_id' => 12],
            ['name' => 'Diretoria Visitação', 'company_id' => 12],
            ['name' => 'Marketing', 'company_id' => 12],
            ['name' => 'Vendas', 'company_id' => 12],
            ['name' => 'Faturamento', 'company_id' => 12],
            ['name' => 'Expedição', 'company_id' => 12],
            ['name' => 'Atendimento Site', 'company_id' => 12],
            ['name' => 'Diretoria Administrativo', 'company_id' => 12],
            ['name' => 'Novos Negócios', 'company_id' => 12],
            ['name' => 'Suprimentos', 'company_id' => 12],
            ['name' => 'Administrativo', 'company_id' => 12],
            ['name' => 'Arquitetura', 'company_id' => 12],
            ['name' => 'Diretoria', 'company_id' => 12],
            ['name' => 'Be Generous ', 'company_id' => 12],
            ['name' => 'Diretoria de Tecnologia', 'company_id' => 12],
            ['name' => 'Software e Sistemas', 'company_id' => 12],
            ['name' => 'Inteligência de Negócio', 'company_id' => 12],
            ['name' => 'Technologies', 'company_id' => 12],
            ['name' => 'Digital', 'company_id' => 12],
            ['name' => 'Infraestrutura e Telecom', 'company_id' => 12],
            ['name' => 'ERP', 'company_id' => 12],
            ['name' => 'Diretoria DDH', 'company_id' => 12],
            ['name' => 'DDH', 'company_id' => 12],
            ['name' => 'Recursos Humanos', 'company_id' => 12],
            ['name' => 'Departamento Pessoal', 'company_id' => 12],
            ['name' => 'Endomarketing', 'company_id' => 12],
            ['name' => 'Diretoria Financeiro', 'company_id' => 12],
            ['name' => 'Financeiro', 'company_id' => 12],
            ['name' => 'Tributário', 'company_id' => 12],
            ['name' => 'P&D', 'company_id' => 12],
            // --- 13
            ['name' => 'Diretoria tributário/Central de notas', 'company_id' => 13],
            ['name' => 'Controladoria', 'company_id' => 13],
            ['name' => 'Diretoria Controladoria', 'company_id' => 13],
            ['name' => 'Central de Notas', 'company_id' => 13],
            ['name' => 'Diretoria P&D', 'company_id' => 13],
            ['name' => 'Almoxarifado E-Commerce', 'company_id' => 13],
            ['name' => 'Atendimento E-Commerce e SAC', 'company_id' => 13],
            ['name' => 'Expedição E-Commerce', 'company_id' => 13],
            ['name' => 'Faturamento E-Commerce', 'company_id' => 13],
            ['name' => 'E-commerce Marketing', 'company_id' => 13],
            ['name' => 'Diretoria de Produção', 'company_id' => 13],
            ['name' => 'PCP (Planejamento de Produção)', 'company_id' => 13],
            ['name' => 'Almoxarifado', 'company_id' => 13],
            ['name' => 'Qualidade', 'company_id' => 13],
            ['name' => 'Manutenção', 'company_id' => 13],
            ['name' => 'Segurança do Trabalho', 'company_id' => 13],
            ['name' => 'Noorskin', 'company_id' => 13],
            ['name' => 'Diretoria Vendas e Marketing', 'company_id' => 13],
            ['name' => 'Visitação', 'company_id' => 13],
            ['name' => 'Trade Marketing', 'company_id' => 13],
            ['name' => 'EAD', 'company_id' => 13],
            ['name' => 'Internacional', 'company_id' => 13],
            ['name' => 'SAC', 'company_id' => 13],
            ['name' => 'Congressos e Eventos', 'company_id' => 13],
            ['name' => 'Diretoria Visitação', 'company_id' => 13],
            ['name' => 'Marketing', 'company_id' => 13],
            ['name' => 'Vendas', 'company_id' => 13],
            ['name' => 'Faturamento', 'company_id' => 13],
            ['name' => 'Expedição', 'company_id' => 13],
            ['name' => 'Atendimento Site', 'company_id' => 13],
            ['name' => 'Diretoria Administrativo', 'company_id' => 13],
            ['name' => 'Novos Negócios', 'company_id' => 13],
            ['name' => 'Suprimentos', 'company_id' => 13],
            ['name' => 'Administrativo', 'company_id' => 13],
            ['name' => 'Arquitetura', 'company_id' => 13],
            ['name' => 'Diretoria', 'company_id' => 13],
            ['name' => 'Be Generous ', 'company_id' => 13],
            ['name' => 'Diretoria de Tecnologia', 'company_id' => 13],
            ['name' => 'Software e Sistemas', 'company_id' => 13],
            ['name' => 'Inteligência de Negócio', 'company_id' => 13],
            ['name' => 'Technologies', 'company_id' => 13],
            ['name' => 'Digital', 'company_id' => 13],
            ['name' => 'Infraestrutura e Telecom', 'company_id' => 13],
            ['name' => 'ERP', 'company_id' => 13],
            ['name' => 'Diretoria DDH', 'company_id' => 13],
            ['name' => 'DDH', 'company_id' => 13],
            ['name' => 'Recursos Humanos', 'company_id' => 13],
            ['name' => 'Departamento Pessoal', 'company_id' => 13],
            ['name' => 'Endomarketing', 'company_id' => 13],
            ['name' => 'Diretoria Financeiro', 'company_id' => 13],
            ['name' => 'Financeiro', 'company_id' => 13],
            ['name' => 'Tributário', 'company_id' => 13],
            ['name' => 'P&D', 'company_id' => 13],
            // --- 14
            ['name' => 'Diretoria tributário/Central de notas', 'company_id' => 14],
            ['name' => 'Controladoria', 'company_id' => 14],
            ['name' => 'Diretoria Controladoria', 'company_id' => 14],
            ['name' => 'Central de Notas', 'company_id' => 14],
            ['name' => 'Diretoria P&D', 'company_id' => 14],
            ['name' => 'Almoxarifado E-Commerce', 'company_id' => 14],
            ['name' => 'Atendimento E-Commerce e SAC', 'company_id' => 14],
            ['name' => 'Expedição E-Commerce', 'company_id' => 14],
            ['name' => 'Faturamento E-Commerce', 'company_id' => 14],
            ['name' => 'E-commerce Marketing', 'company_id' => 14],
            ['name' => 'Diretoria de Produção', 'company_id' => 14],
            ['name' => 'PCP (Planejamento de Produção)', 'company_id' => 14],
            ['name' => 'Almoxarifado', 'company_id' => 14],
            ['name' => 'Qualidade', 'company_id' => 14],
            ['name' => 'Manutenção', 'company_id' => 14],
            ['name' => 'Segurança do Trabalho', 'company_id' => 14],
            ['name' => 'Noorskin', 'company_id' => 14],
            ['name' => 'Diretoria Vendas e Marketing', 'company_id' => 14],
            ['name' => 'Visitação', 'company_id' => 14],
            ['name' => 'Trade Marketing', 'company_id' => 14],
            ['name' => 'EAD', 'company_id' => 14],
            ['name' => 'Internacional', 'company_id' => 14],
            ['name' => 'SAC', 'company_id' => 14],
            ['name' => 'Congressos e Eventos', 'company_id' => 14],
            ['name' => 'Diretoria Visitação', 'company_id' => 14],
            ['name' => 'Marketing', 'company_id' => 14],
            ['name' => 'Vendas', 'company_id' => 14],
            ['name' => 'Faturamento', 'company_id' => 14],
            ['name' => 'Expedição', 'company_id' => 14],
            ['name' => 'Atendimento Site', 'company_id' => 14],
            ['name' => 'Diretoria Administrativo', 'company_id' => 14],
            ['name' => 'Novos Negócios', 'company_id' => 14],
            ['name' => 'Suprimentos', 'company_id' => 14],
            ['name' => 'Administrativo', 'company_id' => 14],
            ['name' => 'Arquitetura', 'company_id' => 14],
            ['name' => 'Diretoria', 'company_id' => 14],
            ['name' => 'Be Generous ', 'company_id' => 14],
            ['name' => 'Diretoria de Tecnologia', 'company_id' => 14],
            ['name' => 'Software e Sistemas', 'company_id' => 14],
            ['name' => 'Inteligência de Negócio', 'company_id' => 14],
            ['name' => 'Technologies', 'company_id' => 14],
            ['name' => 'Digital', 'company_id' => 14],
            ['name' => 'Infraestrutura e Telecom', 'company_id' => 14],
            ['name' => 'ERP', 'company_id' => 14],
            ['name' => 'Diretoria DDH', 'company_id' => 14],
            ['name' => 'DDH', 'company_id' => 14],
            ['name' => 'Recursos Humanos', 'company_id' => 14],
            ['name' => 'Departamento Pessoal', 'company_id' => 14],
            ['name' => 'Endomarketing', 'company_id' => 14],
            ['name' => 'Diretoria Financeiro', 'company_id' => 14],
            ['name' => 'Financeiro', 'company_id' => 14],
            ['name' => 'Tributário', 'company_id' => 14],
            ['name' => 'P&D', 'company_id' => 14],
            // --- 15
            ['name' => 'Diretoria tributário/Central de notas', 'company_id' => 15],
            ['name' => 'Controladoria', 'company_id' => 15],
            ['name' => 'Diretoria Controladoria', 'company_id' => 15],
            ['name' => 'Central de Notas', 'company_id' => 15],
            ['name' => 'Diretoria P&D', 'company_id' => 15],
            ['name' => 'Almoxarifado E-Commerce', 'company_id' => 15],
            ['name' => 'Atendimento E-Commerce e SAC', 'company_id' => 15],
            ['name' => 'Expedição E-Commerce', 'company_id' => 15],
            ['name' => 'Faturamento E-Commerce', 'company_id' => 15],
            ['name' => 'E-commerce Marketing', 'company_id' => 15],
            ['name' => 'Diretoria de Produção', 'company_id' => 15],
            ['name' => 'PCP (Planejamento de Produção)', 'company_id' => 15],
            ['name' => 'Almoxarifado', 'company_id' => 15],
            ['name' => 'Qualidade', 'company_id' => 15],
            ['name' => 'Manutenção', 'company_id' => 15],
            ['name' => 'Segurança do Trabalho', 'company_id' => 15],
            ['name' => 'Noorskin', 'company_id' => 15],
            ['name' => 'Diretoria Vendas e Marketing', 'company_id' => 15],
            ['name' => 'Visitação', 'company_id' => 15],
            ['name' => 'Trade Marketing', 'company_id' => 15],
            ['name' => 'EAD', 'company_id' => 15],
            ['name' => 'Internacional', 'company_id' => 15],
            ['name' => 'SAC', 'company_id' => 15],
            ['name' => 'Congressos e Eventos', 'company_id' => 15],
            ['name' => 'Diretoria Visitação', 'company_id' => 15],
            ['name' => 'Marketing', 'company_id' => 15],
            ['name' => 'Vendas', 'company_id' => 15],
            ['name' => 'Faturamento', 'company_id' => 15],
            ['name' => 'Expedição', 'company_id' => 15],
            ['name' => 'Atendimento Site', 'company_id' => 15],
            ['name' => 'Diretoria Administrativo', 'company_id' => 15],
            ['name' => 'Novos Negócios', 'company_id' => 15],
            ['name' => 'Suprimentos', 'company_id' => 15],
            ['name' => 'Administrativo', 'company_id' => 15],
            ['name' => 'Arquitetura', 'company_id' => 15],
            ['name' => 'Diretoria', 'company_id' => 15],
            ['name' => 'Be Generous ', 'company_id' => 15],
            ['name' => 'Diretoria de Tecnologia', 'company_id' => 15],
            ['name' => 'Software e Sistemas', 'company_id' => 15],
            ['name' => 'Inteligência de Negócio', 'company_id' => 15],
            ['name' => 'Technologies', 'company_id' => 15],
            ['name' => 'Digital', 'company_id' => 15],
            ['name' => 'Infraestrutura e Telecom', 'company_id' => 15],
            ['name' => 'ERP', 'company_id' => 15],
            ['name' => 'Diretoria DDH', 'company_id' => 15],
            ['name' => 'DDH', 'company_id' => 15],
            ['name' => 'Recursos Humanos', 'company_id' => 15],
            ['name' => 'Departamento Pessoal', 'company_id' => 15],
            ['name' => 'Endomarketing', 'company_id' => 15],
            ['name' => 'Diretoria Financeiro', 'company_id' => 15],
            ['name' => 'Financeiro', 'company_id' => 15],
            ['name' => 'Tributário', 'company_id' => 15],
            ['name' => 'P&D', 'company_id' => 15],
            // --- 16
            ['name' => 'Diretoria Financeiro', 'company_id' => 16],
            ['name' => 'Financeiro', 'company_id' => 16],
            ['name' => 'Diretoria Tributário/Central de notas', 'company_id' => 16],
            ['name' => 'Diretoria Controladoria', 'company_id' => 16],
            ['name' => 'Tributário', 'company_id' => 16],
            ['name' => 'Controladoria', 'company_id' => 16],
            ['name' => 'Central de Notas', 'company_id' => 16],
            ['name' => 'Diretoria P&D', 'company_id' => 16],
            ['name' => 'P&D', 'company_id' => 16],
            ['name' => 'Diretoria de Produção', 'company_id' => 16],
            ['name' => 'PCP (Planejamento de Produção)', 'company_id' => 16],
            ['name' => 'Almoxarifado', 'company_id' => 16],
            ['name' => 'Qualidade', 'company_id' => 16],
            ['name' => 'Manutenção (produção)', 'company_id' => 16],
            ['name' => 'Segurança do Trabalho', 'company_id' => 16],
            ['name' => 'Limpeza (produção)', 'company_id' => 16],
            ['name' => 'Diretoria Vendas e Marketing', 'company_id' => 16],
            ['name' => 'Visitação', 'company_id' => 16],
            ['name' => 'Trade Marketing', 'company_id' => 16],
            ['name' => 'EAD', 'company_id' => 16],
            ['name' => 'Internacional', 'company_id' => 16],
            ['name' => 'SAC', 'company_id' => 16],
            ['name' => 'Congressos e Eventos', 'company_id' => 16],
            ['name' => 'Marketing', 'company_id' => 16],
            ['name' => 'Vendas', 'company_id' => 16],
            ['name' => 'Faturamento', 'company_id' => 16],
            ['name' => 'Expedição', 'company_id' => 16],
            ['name' => 'Atendimento Site', 'company_id' => 16],
            ['name' => 'Diretoria Administrativo', 'company_id' => 16],
            ['name' => 'Suprimentos', 'company_id' => 16],
            ['name' => 'Administrativo', 'company_id' => 16],
            ['name' => 'Limpeza (administrativo)', 'company_id' => 16],
            ['name' => 'Manutenção (adminstrativo)', 'company_id' => 16],
            ['name' => 'Projetos', 'company_id' => 16],
            ['name' => 'Diretoria', 'company_id' => 16],
            ['name' => 'Be Generous', 'company_id' => 16],
            ['name' => 'Diretoria de Tecnologia', 'company_id' => 16],
            ['name' => 'T.I Interno', 'company_id' => 16],
            ['name' => 'Digital', 'company_id' => 16],
            ['name' => 'Software e Sistemas', 'company_id' => 16],
            ['name' => 'Inteligência de Negócio', 'company_id' => 16],
            ['name' => 'Infraestrutura e Telecom', 'company_id' => 16],
            ['name' => 'ERP', 'company_id' => 16],
            ['name' => 'Diretoria DDH', 'company_id' => 16],
            ['name' => 'DDH', 'company_id' => 16],
            ['name' => 'Recursos Humanos', 'company_id' => 16],
            ['name' => 'Departamento Pessoal', 'company_id' => 16],
            ['name' => 'Endomarketing', 'company_id' => 16],
            // --- 17
            ['name' => 'Diretoria Financeiro', 'company_id' => 17],
            ['name' => 'Financeiro', 'company_id' => 17],
            ['name' => 'Diretoria Tributário/Central de notas', 'company_id' => 17],
            ['name' => 'Diretoria Controladoria', 'company_id' => 17],
            ['name' => 'Tributário', 'company_id' => 17],
            ['name' => 'Controladoria', 'company_id' => 17],
            ['name' => 'Central de Notas', 'company_id' => 17],
            ['name' => 'Diretoria P&D', 'company_id' => 17],
            ['name' => 'P&D', 'company_id' => 17],
            ['name' => 'Diretoria de Produção', 'company_id' => 17],
            ['name' => 'PCP (Planejamento de Produção)', 'company_id' => 17],
            ['name' => 'Almoxarifado', 'company_id' => 17],
            ['name' => 'Qualidade', 'company_id' => 17],
            ['name' => 'Manutenção (produção)', 'company_id' => 17],
            ['name' => 'Segurança do Trabalho', 'company_id' => 17],
            ['name' => 'Limpeza (produção)', 'company_id' => 17],
            ['name' => 'Diretoria Vendas e Marketing', 'company_id' => 17],
            ['name' => 'Visitação', 'company_id' => 17],
            ['name' => 'Trade Marketing', 'company_id' => 17],
            ['name' => 'EAD', 'company_id' => 17],
            ['name' => 'Internacional', 'company_id' => 17],
            ['name' => 'SAC', 'company_id' => 17],
            ['name' => 'Congressos e Eventos', 'company_id' => 17],
            ['name' => 'Marketing', 'company_id' => 17],
            ['name' => 'Vendas', 'company_id' => 17],
            ['name' => 'Faturamento', 'company_id' => 17],
            ['name' => 'Expedição', 'company_id' => 17],
            ['name' => 'Atendimento Site', 'company_id' => 17],
            ['name' => 'Diretoria Administrativo', 'company_id' => 17],
            ['name' => 'Suprimentos', 'company_id' => 17],
            ['name' => 'Administrativo', 'company_id' => 17],
            ['name' => 'Limpeza (administrativo)', 'company_id' => 17],
            ['name' => 'Manutenção (adminstrativo)', 'company_id' => 17],
            ['name' => 'Projetos', 'company_id' => 17],
            ['name' => 'Diretoria', 'company_id' => 17],
            ['name' => 'Be Generous', 'company_id' => 17],
            ['name' => 'Diretoria de Tecnologia', 'company_id' => 17],
            ['name' => 'T.I Interno', 'company_id' => 17],
            ['name' => 'Digital', 'company_id' => 17],
            ['name' => 'Software e Sistemas', 'company_id' => 17],
            ['name' => 'Inteligência de Negócio', 'company_id' => 17],
            ['name' => 'Infraestrutura e Telecom', 'company_id' => 17],
            ['name' => 'ERP', 'company_id' => 17],
            ['name' => 'Diretoria DDH', 'company_id' => 17],
            ['name' => 'DDH', 'company_id' => 17],
            ['name' => 'Recursos Humanos', 'company_id' => 17],
            ['name' => 'Departamento Pessoal', 'company_id' => 17],
            ['name' => 'Endomarketing', 'company_id' => 17],
            // --- 18
            ['name' => 'Revenda', 'company_id' => 18],
            ['name' => 'Almoxarifado', 'company_id' => 18],
            ['name' => 'Limpeza (produção)', 'company_id' => 18],
            ['name' => 'Manutenção (produção)', 'company_id' => 18],
            ['name' => 'Qualidade', 'company_id' => 18],
            ['name' => 'Segurança do Trabalho', 'company_id' => 18],
            ['name' => 'Noorskin', 'company_id' => 18],
            ['name' => 'Receitas para Vendas', 'company_id' => 18],
            ['name' => 'Atendimento E-Commerce e SAC', 'company_id' => 18],
            ['name' => 'Congressos e Eventos', 'company_id' => 18],
            ['name' => 'Diretoria Vendas e Marketing', 'company_id' => 18],
            ['name' => 'Expedição', 'company_id' => 18],
            ['name' => 'Faturamento', 'company_id' => 18],
            ['name' => 'Marketing', 'company_id' => 18],
            ['name' => 'Recepção', 'company_id' => 18],
            ['name' => 'Visitação', 'company_id' => 18],
            ['name' => 'Diretoria Administrativo', 'company_id' => 18],
            ['name' => 'Suprimentos', 'company_id' => 18],
            ['name' => 'Novos Projetos', 'company_id' => 18],
            ['name' => 'Diretoria', 'company_id' => 18],
            ['name' => 'Infraestrutura e Telecom', 'company_id' => 18],
            ['name' => 'TI Technologies', 'company_id' => 18],
            ['name' => 'DDH', 'company_id' => 18],
            ['name' => 'Financeiro', 'company_id' => 18],
            ['name' => 'Diretoria financeira', 'company_id' => 18],
            ['name' => 'Tributário', 'company_id' => 18],
            ['name' => 'Controladoria', 'company_id' => 18],
        ];

        DB::table('cost_centers')->insert($costCenters);
    }
}
