/// <reference path="./support/cypress.d.ts" />


import { faker } from '@faker-js/faker';
import * as fakerBr from 'faker-br';
import { format } from 'date-fns';



const ambiente = Cypress.env('AMBIENTE');
const dadosAmbiente = Cypress.env(ambiente);


export interface DataHora<T = string> {
    DATA_FORMATADA: T;
    HORA_FORMATADA: T;
}


export type ValidationResult = Cypress.Chainable<{
    error?: string;
    success?: string;
}>


interface DadosParametros<T = string> {

    sizes: Array<number | [number, number] | string>;

    env: {
        ENV: T;
        EMAILADMIN: T;
        SENHAADMIN: T;
        EMAILUSUARIO: T;
        SENHAUSUARIO: T;
        EMAILGESTORUSUARIO: T;
        SENHAGESTORUSUARIO: T;
        BASEURL: T;
        DB_NAME: T;
        DB_USER: T;
        DB_HOST: T;
        DB_PORT: T;
        DB_PASSWORD: T;
    };

    url: {
        login: T;
    };

    Autenticacao: {
        dominio: T;
        email: T;
        senha: T;
        senhaGigante: T;
    };

    Cadastro: {
        nome: T;
        letraUnica: T;
        cpf: T;
        cnpj: T;
        telefone: T;
    };

    cadastroParams: {
        nome: T;
        dataNascimento: Date;
        cpf: number;
        cnpj: number;
        telefone: T;
        email: T;
        senha: T;
        senhaGigante: T;
        perfilUsuario: PerfilUsuario;
        autorizacaoSolicitar: T;
        solicitarOutrasPessoas: T;
        setor: SetorCentroCustoPermitido;
        usuarioAprovador: UsuarioAprovador;
        limiteAprovacao: number;
        centroCustoPermitido: SetorCentroCustoPermitido;
    };

    enums: {
        PerfilUsuario: typeof PerfilUsuario;
        AutorizacaoSolicitar: typeof AutorizacaoSolicitar;
        SolicitarOutrasPessoas: typeof SolicitarOutrasPessoas;
        SetorCentroCustoPermitido: typeof SetorCentroCustoPermitido;
        UsuarioAprovador: typeof UsuarioAprovador;
    };
}



export const getRandomValue = <T>(array: T[]): T => {
    const randomIndex = Math.floor(Math.random() * array.length);
    return array[randomIndex];
};

enum PerfilUsuario {
    Administrador = "profile_admin",
    Normal = "profile_normal",
    SuprimentosHKM = "profile_suprimentos_hkm",
    SuprimentosINP = "profile_suprimentos_inp",
    GestorUsuarios = "gestor_usuarios",
    GestorFornecedores = "gestor_fornecedores",
};


enum AutorizacaoSolicitar {
    Autorizado = '1',
    NaoAutorizado = '0',
};

enum SolicitarOutrasPessoas {
    Sim = '[data-cy="can-associate-requester"]',
    Nao = '[data-cy="can-not-associate-requester"]',
};

enum SetorCentroCustoPermitido {
    SelecioneOpcao = 0,
    HKMLabSolidos = 1,
    HKMMaterialAplicado = 2,
    HKMRevenda = 3,
    HKMLabInjetaveis = 4,
    HKMLabHormonios = 5,
    HKMLabLiquidos = 6,
    HKMAlmoxarifado = 7,
    HKMConferenciaEntrada = 8,
    HKMConferenciaSaida = 9,
    HKMDiretoriaProducao = 10,
    HKMInclusao = 11,
    HKMLimpeza = 12,
    HKMManutencao = 13,
    HKMQualidade = 14,
    HKMSegurancaTrabalho = 15,
    HKMNoorskin = 16,
    HKMReceitasVendas = 17,
    HKMTeleAtendimento = 18,
    HKMCongressosEventos = 19,
    HKMDiretoriaVendasMarketing = 20,
    HKMExpedicao = 21,
    HKMFaturamentoCaixa = 22,
    HKMMarketing = 23,
    HKMRecepcao = 24,
    HKMVisitação = 25,
    HKMComercialInjetaveis = 26,
    HKMDiretoriaVisitação = 27,
    HKMAdministrativoTerroHKM = 28,
    HKMDiretoriaAdministrativo = 29,
    HKMSuprimentos = 30,
    HKMDiretoria = 31,
    HKMInfraestruturaTelecom = 32,
    HKMDiretoriaTecnologia = 33,
    HKMTITechnologies = 34,
    HKMSoftwareSistemas = 35,
    HKMInteligenciaNegocio = 36,
    HKMDigital = 37,
    HKMERP = 38,
    HKMDDH = 39,
    HKMDiretoriaDDH = 40,
    HKMRecursosHumanos = 41,
    HKMDepartamentoPessoal = 42,
    HKMEndomarketing = 43,
    HKMFinanceiro = 44,
    HKMDiretoriaFinanceira = 45,
    HKMTributario = 46,
    HKMControladoria = 47,
    HKMPeD = 48,
    SMARTMATRIZMaterialAplicado = 49,
    SMARTMATRIZLabInjetaveis = 50,
    SMARTMATRIZRevenda = 51,
    SMARTMATRIZLabHormonios = 52,
    SMARTMATRIZLabLiquidos = 53,
    SMARTMATRIZLabSolidos = 54,
    SMARTMATRIZConferenciaEntrada = 55,
    SMARTMATRIZConferenciaSaida = 56,
    SMARTMATRIZDiretoriaProducao = 57,
    SMARTMATRIZInclusao = 58,
    SMARTMATRIZLimpeza = 59,
    SMARTMATRIZManutencao = 60,
    SMARTMATRIZQualidade = 61,
    SMARTMATRIZSegurancaTrabalho = 62,
    SMARTMATRIZAlmoxarifado = 63,
    SMARTMATRIZNoorskin = 64,
    SMARTMATRIZReceitaVendas = 65,
    SMARTMATRIZAtendimento = 66,
    SMARTMATRIZCongressosEventos = 67,
    SMARTMATRIZDiretoriaVendasMarketing = 68,
    SMARTMATRIZExpedicao = 69,
    SMARTMATRIZFaturamentoCaixa = 70,
    SMARTMATRIZMarketing = 71,
    SMARTMATRIZVisitação = 72,
    SMARTMATRIZTeleAtendimento = 73,
    SMARTMATRIZAdministrativo = 74,
    SMARTMATRIZDiretoriaAdministrativo = 75,
    SMARTMATRIZSuprimentos = 76,
    SMARTMATRIZDiretoria = 77,
    SMARTMATRIZInfraestruturaTelecom = 78,
    SMARTMATRIZSoftwareSistemas = 79,
    SMARTMATRIZInteligenciaNegocio = 80,
    SMARTMATRIZTITechnologies = 81,
    SMARTMATRIZDigital = 82,
    SMARTMATRIZERP = 83,
    SMARTMATRIZDDH = 84,
    SMARTMATRIZRecursosHumanos = 85,
    SMARTMATRIZDepartamentoPessoal = 86,
    SMARTMATRIZFinanceiro = 87,
    SMARTMATRIZDiretoriaFinanceira = 88,
    SMARTMATRIZTributario = 89,
    SMARTMATRIZControladoria = 90,
    SMARTMATRIZPeD = 91,
    SMARTFILIAL1MaterialAplicado = 92,
    SMARTFILIAL1LabInjetaveis = 93,
    SMARTFILIAL1Revenda = 94,
    SMARTFILIAL1LabHormonios = 95,
    SMARTFILIAL1LabLiquidos = 96,
    SMARTFILIAL1LabSolidos = 97,
    SMARTFILIAL1ConferenciaEntrada = 98,
    SMARTFILIAL1ConferenciaSaida = 99,
    SMARTFILIAL1DiretoriaProducao = 100,
    SMARTFILIAL1Inclusao = 101,
    SMARTFILIAL1Limpeza = 102,
    SMARTFILIAL1Manutencao = 103,
    SMARTFILIAL1Qualidade = 104,
    SMARTFILIAL1SegurancaTrabalho = 105,
    SMARTFILIAL1Almoxarifado = 106,
    SMARTFILIAL1Noorskin = 107,
    SMARTFILIAL1ReceitaVendas = 108,
    SMARTFILIAL1Atendimento = 109,
    SMARTFILIAL1CongressosEventos = 110,
    SMARTFILIAL1DiretoriaVendasMarketing = 111,
    SMARTFILIAL1Expedicao = 112,
    SMARTFILIAL1FaturamentoCaixa = 113,
    SMARTFILIAL1Marketing = 114,
    SMARTFILIAL1Visitação = 115,
    SMARTFILIAL1TeleAtendimento = 116,
    SMARTFILIAL1Administrativo = 117,
    SMARTFILIAL1DiretoriaAdministrativo = 118,
    SMARTFILIAL1Suprimentos = 119,
    SMARTFILIAL1Diretoria = 120,
    SMARTFILIAL1InfraestruturaTelecom = 121,
    SMARTFILIAL1SoftwareSistemas = 122,
    SMARTFILIAL1InteligenciaNegocio = 123,
    SMARTFILIAL1TITechnologies = 124,
    SMARTFILIAL1Digital = 125,
    SMARTFILIAL1ERP = 126,
    SMARTFILIAL1DDH = 127,
    SMARTFILIAL1RecursosHumanos = 128,
    SMARTFILIAL1DepartamentoPessoal = 129,
    SMARTFILIAL1Financeiro = 130,
    SMARTFILIAL1DiretoriaFinanceira = 131,
    SMARTFILIAL1Tributario = 132,
    SMARTFILIAL1Controladoria = 133,
    SMARTFILIAL1PeD = 134,
    SMARTFILIAL2MaterialAplicado = 135,
    SMARTFILIAL2LabInjetaveis = 136,
    SMARTFILIAL2Revenda = 137,
    SMARTFILIAL2LabHormonios = 138,
    SMARTFILIAL2LabLiquidos = 139,
    SMARTFILIAL2LabSolidos = 140,
    SMARTFILIAL2ConferenciaEntrada = 141,
    SMARTFILIAL2ConferenciaSaida = 142,
    SMARTFILIAL2DiretoriaProducao = 143,
    SMARTFILIAL2Inclusao = 144,
    SMARTFILIAL2Limpeza = 145,
    SMARTFILIAL2Manutencao = 146,
    SMARTFILIAL2Qualidade = 147,
    SMARTFILIAL2SegurancaTrabalho = 148,
    SMARTFILIAL2Almoxarifado = 149,
    SMARTFILIAL2Noorskin = 150,
    SMARTFILIAL2ReceitaVendas = 151,
    SMARTFILIAL2Atendimento = 152,
    SMARTFILIAL2CongressosEventos = 153,
    SMARTFILIAL2DiretoriaVendasMarketing = 154,
    SMARTFILIAL2Expedicao = 155,
    SMARTFILIAL2FaturamentoCaixa = 156,
    SMARTFILIAL2Marketing = 157,
    SMARTFILIAL2Visitação = 158,
    SMARTFILIAL2TeleAtendimento = 159,
    SMARTFILIAL2Administrativo = 160,
    SMARTFILIAL2DiretoriaAdministrativo = 161,
    SMARTFILIAL2Suprimentos = 162,
    SMARTFILIAL2Diretoria = 163,
    SMARTFILIAL2InfraestruturaTelecom = 164,
    SMARTFILIAL2SoftwareSistemas = 165,
    SMARTFILIAL2InteligenciaNegocio = 166,
    SMARTFILIAL2TITechnologies = 167,
    SMARTFILIAL2Digital = 168,
    SMARTFILIAL2ERP = 169,
    SMARTFILIAL2DDH = 170,
    SMARTFILIAL2RecursosHumanos = 171,
    SMARTFILIAL2DepartamentoPessoal = 172,
    SMARTFILIAL2Financeiro = 173,
    SMARTFILIAL2DiretoriaFinanceira = 174,
    SMARTFILIAL2Tributario = 175,
    SMARTFILIAL2Controladoria = 176,
    SMARTFILIAL2PeD = 177,
    KLQTECHNOLOGIESRevenda = 178,
    KLQTECHNOLOGIESAlmoxarifado = 179,
    KLQTECHNOLOGIESLimpezaProducao = 180,
    KLQTECHNOLOGIESManutencaoProducao = 181,
    KLQTECHNOLOGIESQualidade = 182,
    KLQTECHNOLOGIESSegurancaTrabalho = 183,
    KLQTECHNOLOGIESNoorskin = 184,
    KLQTECHNOLOGIESReceitasVendas = 185,
    KLQTECHNOLOGIESAtendimentoECommerceSAC = 186,
    KLQTECHNOLOGIESCongressosEventos = 187,
    KLQTECHNOLOGIESDiretoriaVendasMarketing = 188,
    KLQTECHNOLOGIESExpedicao = 189,
    KLQTECHNOLOGIESFaturamento = 190,
    KLQTECHNOLOGIESMarketing = 191,
    KLQTECHNOLOGIESRecepcao = 192,
    KLQTECHNOLOGIESVisitação = 193,
    KLQTECHNOLOGIESDiretoriaAdministrativo = 194,
    KLQTECHNOLOGIESSuprimentos = 195,
    KLQTECHNOLOGIESNovosProjetos = 196,
    KLQTECHNOLOGIESDiretoria = 197,
    KLQTECHNOLOGIESInfraestruturaTelecom = 198,
    KLQTECHNOLOGIESTITechnologies = 199,
    KLQTECHNOLOGIESDDH = 200,
    KlqTechnologiesFinanceiro = 201,
    KlqTechnologiesDiretoriaFinanceira = 202,
    KlqTechnologiesTributario = 203,
    KlqTechnologiesControladoria = 204,
    JmlRevenda = 205,
    JmlAlmoxarifado = 206,
    JmlLimpeza = 207,
    JmlManutencao = 208,
    JmlQualidade = 209,
    JmlSegurancaTrabalho = 210,
    JmlReceitasVendas = 211,
    JmlAtendimentoECommerceSAC = 212,
    JmlCongressosEventos = 213,
    JmlDiretoriaVendasMarketing = 214,
    JmlExpedicao = 215,
    JmlFaturamento = 216,
    JmlMarketing = 217,
    JmlRecepcao = 218,
    JmlVisitação = 219,
    JmlContabilidade = 220,
    JmlDDH = 221,
    JmlDiretoriaAdministrativoFinanceiro = 222,
    JmlFinanceiro = 223,
    JmlSuprimentos = 224,
    JmlTI = 225,
    RshdRevenda = 226,
    RshdAlmoxarifado = 227,
    RshdLimpezaProducao = 228,
    RshdManutencaoProducao = 229,
    RshdQualidade = 230,
    RshdSegurancaTrabalho = 231,
    RshdNoorskin = 232,
    RshdReceitasVendas = 233,
    RshdAtendimentoECommerceSAC = 234,
    RshdCongressosEventos = 235,
    RshdDiretoriaVendasMarketing = 236,
    RshdExpedicao = 237,
    RshdFaturamento = 238,
    RshdMarketing = 239,
    RshdRecepcao = 240,
    RshdVisitação = 241,
    RshdDiretoriaAdministrativo = 242,
    RshdSuprimentos = 243,
    RshdNovosProjetos = 244,
    RshdDiretoria = 245,
    RshdInfraestruturaTelecom = 246,
    RshdTITechnologies = 247,
    RshdDDH = 248,
    RshdFinanceiro = 249,
    RshdDiretoriaFinanceira = 250,
    RshdTributario = 251,
    RshdControladoria = 252,
    CgeRevenda = 253,
    CgeAlmoxarifado = 254,
    CgeLimpezaProducao = 255,
    CgeManutencaoProducao = 256,
    CgeQualidade = 257,
    CgeSegurancaTrabalho = 258,
    CgeNoorskin = 259,
    CgeReceitasVendas = 260,
    CgeAtendimentoECommerceSAC = 261,
    CgeCongressosEventos = 262,
    CgeDiretoriaVendasMarketing = 263,
    CgeExpedicao = 264,
    CgeFaturamento = 265,
    CgeMarketing = 266,
    CgeRecepcao = 267,
    CgeVisitação = 268,
    CgeDiretoriaAdministrativo = 269,
    CgeSuprimentos = 270,
    CgeNovosProjetos = 271,
    CgeDiretoria = 272,
    CgeInfraestruturaTelecom = 273,
    CgeTITechnologies = 274,
    CgeDDH = 275,
    CgeFinanceiro = 276,
    CgeDiretoriaFinanceira = 277,
    CgeTributario = 278,
    CgeControladoria = 279,
    ShfRevenda = 280,
    ShfAlmoxarifado = 281,
    ShfLimpezaProducao = 282,
    ShfManutencaoProducao = 283,
    ShfQualidade = 284,
    ShfSegurancaTrabalho = 285,
    ShfNoorskin = 286,
    ShfReceitasVendas = 287,
    ShfAtendimentoECommerceSAC = 288,
    ShfCongressosEventos = 289,
    ShfDiretoriaVendasMarketing = 290,
    ShfExpedicao = 291,
    ShfFaturamento = 292,
    ShfMarketing = 293,
    ShfRecepcao = 294,
    ShfVisitação = 295,
    ShfDiretoriaAdministrativo = 296,
    ShfSuprimentos = 297,
    ShfNovosProjetos = 298,
    ShfDiretoria = 299,
    ShfInfraestruturaTelecom = 300,
    SHFTITechnologies = 301,
    SHFDDH = 302,
    SHFFinanceiro = 303,
    SHFDiretoriaFinanceira = 304,
    SHFTributario = 305,
    SHFControladoria = 306,
    MTNRevenda = 307,
    MTNAlmoxarifado = 308,
    MTNLimpezaProducao = 309,
    MTNManutencaoProducao = 310,
    MTNQualidade = 311,
    MTNSegurancaTrabalho = 312,
    MTNNoorskin = 313,
    MTNReceitasVendas = 314,
    MTNAtendimentoECommerceSAC = 315,
    MTNCongressosEventos = 316,
    MTNDiretoriaVendasMarketing = 317,
    MTNExpedicao = 318,
    MTNFaturamento = 319,
    MTNMarketing = 320,
    MTNRecepcao = 321,
    MTNVisitação = 322,
    MTNDiretoriaAdministrativo = 323,
    MTNSuprimentos = 324,
    MTNNovosProjetos = 325,
    MTNDiretoria = 326,
    MTNInfraestruturaTelecom = 327,
    MTNTITechnologies = 328,
    MTNDDH = 329,
    MTNFinanceiro = 330,
    MTNDiretoriaFinanceira = 331,
    MTNTributario = 332,
    MTNControladoria = 333,
    INPMatrizProducaoPesagemMistura = 334,
    INPMatrizProducaoMoinho = 335,
    INPMatrizProducaoEnvaseRotulagem = 336,
    INPMatrizProducaoEncartuchamento = 337,
    INPMatrizProducaoEnsacadora = 338,
    INPMatrizDiretoriaTributarioCentralNotas = 339,
    INPMatrizControladoria = 340,
    INPMatrizDiretoriaControladoria = 341,
    INPMatrizCentralNotas = 342,
    INPMatrizDiretoriaPD = 343,
    INPMatrizAlmoxarifadoECommerce = 344,
    INPMatrizAtendimentoECommerceSAC = 345,
    INPMatrizExpedicaoECommerce = 346,
    INPMatrizFaturamentoECommerce = 347,
    INPMatrizECommerceMarketing = 348,
    INPMatrizDiretoriaProducao = 349,
    INPMatrizPCPPlanejamentoProducao = 350,
    INPMatrizAlmoxarifado = 351,
    INPMatrizQualidade = 352,
    INPMatrizManutencao = 353,
    INPMatrizSegurancaTrabalho = 354,
    INPMatrizLimpeza = 355,
    INPMatrizNoorskin = 356,
    INPMatrizDiretoriaVendasMarketing = 357,
    INPMatrizVisitação = 358,
    INPMatrizTradeMarketing = 359,
    INPMatrizEAD = 360,
    INPMatrizInternacional = 361,
    INPMatrizSAC = 362,
    INPMatrizCongressosEventos = 363,
    INPMatrizDiretoriaVisitação = 364,
    INPMatrizMarketing = 365,
    INPMatrizVendas = 366,
    INPMatrizFaturamento = 367,
    INPMatrizExpedicao = 368,
    INPMatrizAtendimentoSite = 369,
    INPMatrizDiretoriaAdministrativo = 370,
    INPMatrizNovosNegocios = 371,
    INPMatrizSuprimentos = 372,
    INPMatrizAdministrativo = 373,
    INPMatrizArquitetura = 374,
    INPMatrizDiretoria = 375,
    INPMatrizBeGenerous = 376,
    INPMatrizDiretoriaTecnologia = 377,
    INPMatrizSoftwareSistemas = 378,
    INPMatrizInteligenciaNegocio = 379,
    INPMatrizTechnologies = 380,
    INPMatrizDigital = 381,
    INPMatrizInfraestruturaTelecom = 382,
    INPMatrizERP = 383,
    INPMatrizDiretoriaDDH = 384,
    INPMatrizDDH = 385,
    INPMatrizRecursosHumanos = 386,
    INPMatrizDepartamentoPessoal = 387,
    INPMatrizEndomarketing = 388,
    INPMatrizDiretoriaFinanceiro = 389,
    INPMatrizFinanceiro = 390,
    INPMatrizTributario = 391,
    INPMatrizPD = 392,
    INPFilialAtriumDiretoriaTributarioCentralNotas = 393,
    INPFilialAtriumControladoria = 394,
    INPFilialAtriumDiretoriaControladoria = 395,
    INPFilialAtriumCentralNotas = 396,
    INPFilialAtriumDiretoriaPD = 397,
    INPFilialAtriumAlmoxarifadoECommerce = 398,
    INPFilialAtriumAtendimentoECommerceSAC = 399,
    INPFilialAtriumExpedicaoECommerce = 400,
    INPFilialAtriumFaturamentoECommerce = 401,
    INPFilialAtriumECommerceMarketing = 402,
    INPFilialAtriumDiretoriaDeProducao = 403,
    INPFilialAtriumPCPPlanejamentoDeProducao = 404,
    INPFilialAtriumAlmoxarifado = 405,
    INPFilialAtriumQualidade = 406,
    INPFilialAtriumManutencao = 407,
    INPFilialAtriumSegurancaDoTrabalho = 408,
    INPFilialAtriumNoorskin = 409,
    INPFilialAtriumDiretoriaVendasEMarketing = 410,
    INPFilialAtriumVisitação = 411,
    INPFilialAtriumTradeMarketing = 412,
    INPFilialAtriumEAD = 413,
    INPFilialAtriumInternacional = 414,
    INPFilialAtriumSAC = 415,
    INPFilialAtriumCongressosEEventos = 416,
    INPFilialAtriumDiretoriaVisitação = 417,
    INPFilialAtriumMarketing = 418,
    INPFilialAtriumVendas = 419,
    INPFilialAtriumFaturamento = 420,
    INPFilialAtriumExpedicao = 421,
    INPFilialAtriumAtendimentoSite = 422,
    INPFilialAtriumDiretoriaAdministrativo = 423,
    INPFilialAtriumNovosNegocios = 424,
    INPFilialAtriumSuprimentos = 425,
    INPFilialAtriumAdministrativo = 426,
    INPFilialAtriumArquitetura = 427,
    INPFilialAtriumDiretoria = 428,
    INPFilialAtriumBeGenerous = 429,
    INPFilialAtriumDiretoriaDeTecnologia = 430,
    INPFilialAtriumSoftwareESistemas = 431,
    INPFilialAtriumInteligenciaDeNegocio = 432,
    INPFilialAtriumTechnologies = 433,
    INPFilialAtriumDigital = 434,
    INPFilialAtriumInfraestruturaETelecom = 435,
    INPFilialAtriumERP = 436,
    INPFilialAtriumDiretoriaDDH = 437,
    INPFilialAtriumDDH = 438,
    INPFilialAtriumRecursosHumanos = 439,
    INPFilialAtriumDepartamentoPessoal = 440,
    INPFilialAtriumEndomarketing = 441,
    INPFilialAtriumDiretoriaFinanceiro = 442,
    INPFilialAtriumFinanceiro = 443,
    INPFilialAtriumTributario = 444,
    INPFilialAtriumPD = 445,
    INPFilialQGSPDiretoriaTributarioCentralNotas = 446,
    INPFilialQGSPControladoria = 447,
    INPFilialQGSPDiretoriaControladoria = 448,
    INPFilialQGSPCentralNotas = 449,
    INPFilialQGSPDiretoriaPD = 450,
    INPFilialQGSPAlmoxarifadoECommerce = 451,
    INPFilialQGSPAtendimentoECommerceESAC = 452,
    INPFilialQGSPOExpedicaoECommerce = 453,
    INPFilialQGSPFaturamentoECommerce = 454,
    INPFilialQGSPECommerceMarketing = 455,
    INPFilialQGSPDiretoriaDeProducao = 456,
    INPFilialQGSPPCPPlanejamentoDeProducao = 457,
    INPFilialQGSPAlmoxarifado = 458,
    INPFilialQGSPQualidade = 459,
    INPFilialQGSPManutencao = 460,
    INPFilialQGSPSegurancaDoTrabalho = 461,
    INPFilialQGSPNoorskin = 462,
    INPFilialQGSPDiretoriaVendasEMarketing = 463,
    INPFilialQGSPVisitação = 464,
    INPFilialQGSPTradeMarketing = 465,
    INPFilialQGSPEAD = 466,
    INPFilialQGSPInternacional = 467,
    INPFilialQGSPSAC = 468,
    INPFilialQGSPCongressosEEventos = 469,
    INPFilialQGSPDiretoriaVisitação = 470,
    INPFilialQGSPMarketing = 471,
    INPFilialQGSPVendas = 472,
    INPFilialQGSPFaturamento = 473,
    INPFilialQGSPExpedicao = 474,
    INPFilialQGSPAtendimentoSite = 475,
    INPFilialQGSPDiretoriaAdministrativo = 476,
    INPFilialQGSPNovosNegocios = 477,
    INPFilialQGSPSuprimentos = 478,
    INPFilialQGSPAdministrativo = 479,
    INPFilialQGSPArquitetura = 480,
    INPFilialQGSPDiretoria = 481,
    INPFilialQGSPBeGenerous = 482,
    INPFilialQGSPDiretoriaDeTecnologia = 483,
    INPFilialQGSPSoftwareESistemas = 484,
    INPFilialQGSPInteligenciaDeNegocio = 485,
    INPFilialQGSPTechnologies = 486,
    INPFilialQGSPDigital = 487,
    INPFilialQGSPInfraestruturaETelecom = 488,
    INPFilialQGSPErp = 489,
    INPFilialQGSPDiretoriaDDH = 490,
    INPFilialQGSPDDH = 491,
    INPFilialQGSPRecursosHumanos = 492,
    INPFilialQGSPDepartamentoPessoal = 493,
    INPFilialQGSPEndomarketing = 494,
    INPFilialQGSPDiretoriaFinanceiro = 495,
    INPFilialQGSPFinanceiro = 496,
    INPFilialQGSPTributario = 497,
    INPFilialQGSPPD = 498,
    INPFilialELANVITAE = 499,
    INPFilialElanVitaeControladoria = 500,
    INPFilialElanVitaeDiretoriaControladoria = 501,
    INPFilialElanVitaeCentralDeNotas = 502,
    INPFilialElanVitaeDiretoriaPD = 503,
    INPFilialElanVitaeAlmoxarifadoECommerce = 504,
    INPFilialElanVitaeAtendimentoECommerceESAC = 505,
    INPFilialElanVitaeExpedicaoECommerce = 506,
    INPFilialElanVitaeFaturamentoECommerce = 507,
    INPFilialElanVitaeECommerceMarketing = 508,
    INPFilialElanVitaeDiretoriaDeProducao = 509,
    INPFilialElanVitaePCPPlanejamentoDeProducao = 510,
    INPFilialElanVitaeAlmoxarifado = 511,
    INPFilialElanVitaeQualidade = 512,
    INPFilialElanVitaeManutencao = 513,
    INPFilialElanVitaeSegurancaDoTrabalho = 514,
    INPFilialElanVitaeNoorskin = 515,
    INPFilialElanVitaeDiretoriaVendasEMarketing = 516,
    INPFilialElanVitaeVisitação = 517,
    INPFilialElanVitaeTradeMarketing = 518,
    INPFilialElanVitaeEAD = 519,
    INPFilialElanVitaeInternacional = 520,
    INPFilialElanVitaeSAC = 521,
    INPFilialElanVitaeCongressosEEventos = 522,
    INPFilialElanVitaeDiretoriaVisitação = 523,
    INPFilialElanVitaeMarketing = 524,
    INPFilialElanVitaeVendas = 525,
    INPFilialElanVitaeFaturamento = 526,
    INPFilialElanVitaeExpedicao = 527,
    INPFilialElanVitaeAtendimentoSite = 528,
    INPFilialElanVitaeDiretoriaAdministrativo = 529,
    INPFilialElanVitaeNovosNegocios = 530,
    INPFilialElanVitaeSuprimentos = 531,
    INPFilialElanVitaeAdministrativo = 532,
    INPFilialElanVitaeArquitetura = 533,
    INPFilialElanVitaeDiretoria = 534,
    INPFilialElanVitaeBeGenerous = 535,
    INPFilialElanVitaeDiretoriaDeTecnologia = 536,
    INPFilialElanVitaeSoftwareESistemas = 537,
    INPFilialElanVitaeInteligenciaDeNegocio = 538,
    INPFilialElanVitaeTechnologies = 539,
    INPFilialElanVitaeDigital = 540,
    INPFilialElanVitaeInfraestruturaETelecom = 541,
    INPFilialElanVitaeERP = 542,
    INPFilialElanVitaeDiretoriaDDH = 543,
    INPFilialElanVitaeDDH = 544,
    INPFilialElanVitaeRecursosHumanos = 545,
    INPFilialElanVitaeDepartamentoPessoal = 546,
    INPFilialElanVitaeEndomarketing = 547,
    INPFilialElanVitaeDiretoriaFinanceiro = 548,
    INPFilialElanVitaeFinanceiro = 549,
    INPFilialElanVitaeTributario = 550,
    INPFilialElanVitaePD = 551,
    INPFilialClinicaSPDiretoriaTributarioCentralNotas = 552,
    INPFilialClinicaSPControladoria = 553,
    INPFilialClinicaSPDiretoriaControladoria = 554,
    INPFilialClinicaSPCentralNotas = 555,
    INPFilialClinicaSPDiretoriaPD = 556,
    INPFilialClinicaSPAlmoxarifadoECommerce = 557,
    INPFilialClinicaSPAtendimentoECommerceESAC = 558,
    INPFilialClinicaSPOExpedicaoECommerce = 559,
    INPFilialClinicaSPFaturamentoECommerce = 560,
    INPFilialClinicaSPECommerceMarketing = 561,
    INPFilialClinicaSPDiretoriaDeProducao = 562,
    INPFilialClinicaSPPCPPlanejamentoDeProducao = 563,
    INPFilialClinicaSPAlmoxarifado = 564,
    INPFilialClinicaSPQualidade = 565,
    INPFilialClinicaSPManutencao = 566,
    INPFilialClinicaSPSegurancaDoTrabalho = 567,
    INPFilialClinicaSPNoorskin = 568,
    INPFilialClinicaSPDiretoriaVendasEMarketing = 569,
    INPFilialClinicaSPVisitação = 570,
    INPFilialClinicaSPTradeMarketing = 571,
    INPFilialClinicaSPEAD = 572,
    INPFilialClinicaSPInternacional = 573,
    INPFilialClinicaSPSAC = 574,
    INPFilialClinicaSPCongressosEEventos = 575,
    INPFilialClinicaSPDiretoriaVisitação = 576,
    INPFilialClinicaSPMarketing = 577,
    INPFilialClinicaSPVendas = 578,
    INPFilialClinicaSPFaturamento = 579,
    INPFilialClinicaSPExpedicao = 580,
    INPFilialClinicaSPAtendimentoSite = 581,
    INPFilialClinicaSPDiretoriaAdministrativo = 582,
    INPFilialClinicaSPNovosNegocios = 583,
    INPFilialClinicaSPSuprimentos = 584,
    INPFilialClinicaSPAdministrativo = 585,
    INPFilialClinicaSPArquitetura = 586,
    INPFilialClinicaSPDiretoria = 587,
    INPFilialClinicaSPBeGenerous = 588,
    INPFilialClinicaSPDiretoriaDeTecnologia = 589,
    INPFilialClinicaSPSoftwareESistemas = 590,
    INPFilialClinicaSPInteligenciaDeNegocio = 591,
    INPFilialClinicaSPTechnologies = 592,
    INPFilialClinicaSPDigital = 593,
    INPFilialClinicaSPInfraestruturaETelecom = 594,
    INPFilialClinicaSPERP = 595,
    INPFilialClinicaSPDiretoriaDDH = 596,
    INPFilialClinicaSPDDH = 597,
    INPFilialClinicaSPRecursosHumanos = 598,
    INPFilialClinicaSPDepartamentoPessoal = 599,
    INPFilialClinicaSPEndomarketing = 600,
    inpFilialClinicaSpDiretoriaFinanceiro = 601,
    inpFilialClinicaSpFinanceiro = 602,
    inpFilialClinicaSpTributario = 603,
    inpFilialClinicaSpPd = 604,
    noorskinDiretoriaFinanceiro = 605,
    noorskinFinanceiro = 606,
    noorskinDiretoriaTributarioCentralDeNotas = 607,
    noorskinDiretoriaControladoria = 608,
    noorskinTributario = 609,
    noorskinControladoria = 610,
    noorskinCentralDeNotas = 611,
    noorskinDiretoriaPd = 612,
    noorskinPd = 613,
    noorskinDiretoriaDeProducao = 614,
    noorskinPcpPlanejamentoDeProducao = 615,
    noorskinAlmoxarifado = 616,
    noorskinQualidade = 617,
    noorskinManutencaoProducao = 618,
    noorskinSegurancaDoTrabalho = 619,
    noorskinLimpezaProducao = 620,
    noorskinDiretoriaVendasEMarketing = 621,
    noorskinVisitação = 622,
    noorskinTradeMarketing = 623,
    noorskinEad = 624,
    noorskinInternacional = 625,
    noorskinSac = 626,
    noorskinCongressosEEventos = 627,
    noorskinMarketing = 628,
    noorskinVendas = 629,
    noorskinFaturamento = 630,
    noorskinExpedicao = 631,
    noorskinAtendimentoSite = 632,
    noorskinDiretoriaAdministrativo = 633,
    noorskinSuprimentos = 634,
    noorskinAdministrativo = 635,
    noorskinLimpezaAdministrativo = 636,
    noorskinManutencaoAdministrativo = 637,
    noorskinProjetos = 638,
    noorskinDiretoria = 639,
    noorskinBeGenerous = 640,
    noorskinDiretoriaDeTecnologia = 641,
    noorskinTiInterno = 642,
    noorskinDigital = 643,
    noorskinSoftwareESistemas = 644,
    noorskinInteligenciaDeNegocio = 645,
    noorskinInfraestruturaETelecom = 646,
    noorskinErp = 647,
    noorskinDiretoriaDdh = 648,
    noorskinDdh = 649,
    noorskinRecursosHumanos = 650,
    noorskinDepartamentoPessoal = 651,
    siteNoorskinDiretoriaFinanceiro = 652,
    siteNoorskinFinanceiro = 653,
    siteNoorskinDiretoriaTributarioCentralDeNotas = 654,
    siteNoorskinDiretoriaControladoria = 655,
    siteNoorskinTributario = 656,
    siteNoorskinControladoria = 657,
    siteNoorskinCentralDeNotas = 658,
    siteNoorskinDiretoriaPd = 659,
    siteNoorskinPd = 660,
    siteNoorskinDiretoriaDeProducao = 661,
    siteNoorskinPcpPlanejamentoDeProducao = 662,
    siteNoorskinAlmoxarifado = 663,
    siteNoorskinQualidade = 664,
    siteNoorskinManutencaoProducao = 665,
    siteNoorskinSegurancaDoTrabalho = 666,
    siteNoorskinLimpezaProducao = 667,
    siteNoorskinDiretoriaVendasEMarketing = 668,
    siteNoorskinVisitação = 669,
    siteNoorskinTradeMarketing = 670,
    siteNoorskinEad = 671,
    siteNoorskinInternacional = 672,
    siteNoorskinSac = 673,
    siteNoorskinCongressosEEventos = 674,
    siteNoorskinMarketing = 675,
    siteNoorskinVendas = 676,
    siteNoorskinFaturamento = 677,
    siteNoorskinExpedicao = 678,
    siteNoorskinAtendimentoSite = 679,
    siteNoorskinDiretoriaAdministrativo = 680,
    siteNoorskinSuprimentos = 681,
    siteNoorskinAdministrativo = 682,
    siteNoorskinLimpezaAdministrativo = 683,
    siteNoorskinManutencaoAdministrativo = 684,
    siteNoorskinProjetos = 685,
    siteNoorskinDiretoria = 686,
    siteNoorskinBeGenerous = 687,
    siteNoorskinDiretoriaDeTecnologia = 689,
    siteNoorskinTiInterno = 689,
    siteNoorskinDigital = 690,
    siteNoorskinSoftwareESistemas = 691,
    siteNoorskinInteligenciaDeNegocio = 692,
    siteNoorskinInfraestruturaETelecom = 693,
    siteNoorskinERP = 694,
    siteNoorskinDiretoriaDDH = 695,
    siteNoorskinDDH = 696,
    siteNoorskinRecursosHumanos = 697,
    siteNoorskinDepartamentoPessoal = 698,
    siteNoorskinEndomarketing = 699,
    oasisRevenda = 700,
    oasisAlmoxarifado = 701,
    oasisLimpezaProducao = 702,
    oasisManutencaoProducao = 703,
    oasisQualidade = 704,
    oasisSegurancaDoTrabalho = 705,
    oasisNoorskin = 706,
    oasisReceitasParaVendas = 707,
    oasisAtendimentoECommerceESAC = 708,
    oasisCongressosEEventos = 709,
    oasisDiretoriaVendasEMarketing = 710,
    oasisExpedicao = 711,
    oasisFaturamento = 712,
    oasisMarketing = 713,
    oasisRecepcao = 714,
    oasisVisitação = 715,
    oasisDiretoriaAdministrativo = 716,
    oasisSuprimentos = 717,
    oasisNovosProjetos = 718,
    oasisDiretoria = 719,
    oasisInfraestruturaETelecom = 720,
    oasisTITechnologies = 721,
    oasisDDH = 722,
    oasisFinanceiro = 723,
    oasisDiretoriaFinanceira = 724,
    oasisTributario = 725,
    oasisControladoria = 726,
    inpFilialAtriumLimpeza = 727,
    humamQuestRevenda = 728,
    humamQuestAlmoxarifado = 729,
    humamQuestLimpezaProducao = 730,
    humamQuestManutencaoProducao = 731,
    humamQuestQualidade = 732,
    humamQuestSegurancaDoTrabalho = 733,
    humamQuestNoorskin = 734,
    humamQuestReceitasParaVendas = 735,
    humamQuestAtendimentoECommerceESAC = 736,
    humamQuestCongressosEEventos = 737,
    humamQuestDiretoriaVendasEMarketing = 738,
    humamQuestExpedicao = 739,
    humamQuestMarketing = 740,
    humamQuestRecepcao = 741,
    humamQuestVisitação = 742,
    humamQuestDiretoriaAdministrativo = 743,
    humamQuestSuprimentos = 744,
    humamQuestNovosProjetos = 745,
    humamQuestDiretoria = 746,
    humamQuestInfraestruturaETelecom = 747,
    humamQuestTITechnologies = 748,
    humamQuestDDH = 749,
    humamQuestFinanceiro = 750,
    humamQuestDiretoriaFinanceira = 751,
    humamQuestTributario = 752,
    humamQuestControladoria = 753,
    humamQuestFaturamento = 754,
    saraceniServicosDeArquiteturaRevenda = 755,
    saraceniServicosDeArquiteturaAlmoxarifado = 756,
    saraceniServicosDeArquiteturaLimpezaProducao = 757,
    saraceniServicosDeArquiteturaManutencaoProducao = 758,
    saraceniServicosDeArquiteturaQualidade = 759,
    saraceniServicosDeArquiteturaSegurancaDoTrabalho = 760,
    saraceniServicosDeArquiteturaNoorskin = 761,
    saraceniServicosDeArquiteturaReceitasParaVendas = 762,
    saraceniServicosDeArquiteturaAtendimentoECommerceESAC = 763,
    saraceniServicosDeArquiteturaCongressosEEventos = 764,
    saraceniServicosDeArquiteturaDiretoriaVendasEMarketing = 765,
    saraceniServicosDeArquiteturaExpedicao = 766,
    saraceniServicosDeArquiteturaFaturamento = 767,
    saraceniServicosDeArquiteturaMarketing = 768,
    saraceniServicosDeArquiteturaRecepcao = 769,
    saraceniServicosDeArquiteturaVisitação = 770,
    saraceniServicosDeArquiteturaDiretoriaAdministrativo = 771,
    saraceniServicosDeArquiteturaSuprimentos = 772,
    saraceniServicosDeArquiteturaNovosProjetos = 773,
    saraceniServicosDeArquiteturaDiretoria = 774,
    saraceniServicosDeArquiteturaInfraestruturaETelecom = 775,
    saraceniServicosDeArquiteturaTITechnologies = 776,
    saraceniServicosDeArquiteturaDDH = 777,
    saraceniServicosDeArquiteturaFinanceiro = 778,
    SaraceniServicosDeArquiteturaDiretoriaFinanceira = 779,
    SaraceniServicosDeArquiteturaTributario = 780,
    SaraceniServicosDeArquiteturaControladoria = 781,
}

enum UsuarioAprovador {
    diretorTeste = 1

}

enum LimiteAprovacao {
    milReais = 1000
}


const dominio = '@essentia.com.br';
const email = faker.internet.userName() + dominio;
const senha = faker.number.int().toString();
const senhaGigante = faker.lorem.word({ length: { min: 100, max: 102 }, strategy: 'longest' });
const telefone = faker.string.alphanumeric('(48) 9####-####');
const nome = faker.person.fullName();
const letraUnica = faker.string.alpha();
const cpf = fakerBr.br.cpf();
const cnpj = fakerBr.br.cnpj();
const dataNascimento = new Date();


export const dadosParametros: DadosParametros = {

    env: dadosAmbiente,

    sizes: [
        [1536, 960],
        [1440, 900],
        [1366, 768],
        [1280, 800],
        [1280, 720],
        [1024, 768],
        [1024, 600],
        [820, 1180],
        [768, 1024],
        [412, 914],
        [414, 896],
        [414, 846],
        [414, 736],
        [414, 736],
        [390, 844],
        [400, 550],
        [375, 812],
        [375, 667],
        [360, 760],
        [320, 568],
        [320, 480],
        [280, 653],
    ],

    url: {
        login: 'http://192.168.0.66:9400/login',
    },

    Autenticacao: {
        dominio: dominio,
        email: faker.internet.userName() + dominio,
        senha: faker.number.int().toString(),
        senhaGigante: faker.lorem.word({ length: { min: 100, max: 102 }, strategy: 'longest' }),
    },

    Cadastro: {
        nome: nome,
        letraUnica: letraUnica,
        cpf: cpf,
        cnpj: cnpj,
        telefone: telefone,

    },

    enums: {
        PerfilUsuario,
        AutorizacaoSolicitar,
        SolicitarOutrasPessoas,
        SetorCentroCustoPermitido,
        UsuarioAprovador,
    },

    cadastroParams: {
        nome: nome,
        dataNascimento: dataNascimento,
        cpf: cpf,
        cnpj: cnpj,
        telefone: telefone,
        email: email,
        senha: senha,
        senhaGigante: senhaGigante,
        perfilUsuario: PerfilUsuario.Normal,
        autorizacaoSolicitar: AutorizacaoSolicitar.Autorizado,
        solicitarOutrasPessoas: SolicitarOutrasPessoas.Sim,
        setor: SetorCentroCustoPermitido.HKMSoftwareSistemas,
        usuarioAprovador: UsuarioAprovador.diretorTeste,
        limiteAprovacao: LimiteAprovacao.milReais,
        centroCustoPermitido: SetorCentroCustoPermitido.HKMControladoria,
    },

};

