name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Configuração e instalação das dependências da aplicação
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, dom, fileinfo, mysql
        coverage: xdebug

    - name: Install PHP dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Generate key
      run: php artisan key:generate

    - name: Setup SQLite database #cria um novo arquivo de banco de dados SQLite em database/database.sqlite e atualiza o arquivo .env para usar a conexão SQLite e o novo banco de dados
      run: |
        touch database/database.sqlite
        echo "DB_CONNECTION=sqlite" >> .env
        echo "DB_DATABASE=database/database.sqlite" >> .env

    - name: Run migrations #Executa migrations
      run: php artisan migrate --force

    - name: Run seeders #Executa seeders
      run: php artisan db:seed --force

    - name: Directory Permissions #Permissões totais de diretório
      run: chmod -R 777 storage bootstrap/cache

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Node.js dependencies
      run: npm install

    - name: Install @popperjs/core #instala popperjs(Teve que ser incluido como dependencia do projeto(npm install @popperjs/core), para que o bootstrap funcione corretamente no front-end)
      run: npm install @popperjs/core

    - name: Build front-end resources
      run: npm run build

    # Configuração e execução dos testes Cypress
    - name: Checkout Cypress tests
      uses: actions/checkout@v2
      with:
        repository: JoseCyDev/Cygecom
        path: cypress
        ref: feature/GC-7

    - name: Install Node.js dependencies for Cypress
      run: npm install
      working-directory: cypress

    - name: Setup Cypress environment variables
      run: 'echo ''{ 
        "ENVIRONMENT": "TEST",
        "TEST": {
          "ENV": "1",
          "BASE_URL": "${{ secrets.TEST_BASE_URL }}"
          }
        }'' > cypress.env.json'
      working-directory: cypress

    - name: Run Cypress tests
      run: npm run login
      working-directory: cypress