name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: brunojoao3/docker-sm:cy-sm-hkm

    env:
      TEST_BASE_URL: http://gerenciador-compras.docker.local:8085
      GH_TOKEN: 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

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: build application
        uses: addnab/docker-run-action@v3
        with:
          image: brunojoao3/docker-sm:php-8.3-franken
          options: >
            --tty
            -v ${{ github.workspace }}:/var/www/gerenciador-compras
            -w /var/www/gerenciador-compras
            -p 8085:8085
            -p 5173:5173
          run: >
            composer install --prefer-dist --no-progress --no-suggest &&
            php -r "file_exists('.env') || copy('.env.example', '.env');" &&
            php artisan key:generate &&
            echo > database/database.sqlite &&
            echo "DB_CONNECTION=sqlite" >> .env &&
            echo "DB_DATABASE=database/database.sqlite" >> .env &&
            php artisan migrate --force &&
            php artisan db:seed --force &&
            chmod -R 777 storage bootstrap/cache &&
            npm install &&
            npm run build &&
            frankenphp run &

      # Configuração e execução dos testes Cypress
      - name: Checkout Cypress tests
        uses: actions/checkout@v2
        with:
          repository: JoseCyDev/Cygecom
          path: cypress
          ref: feature/GC-7
          token: ${{ env.GH_TOKEN }}

      - name: Install Node.js dependencies for Cypress
        run: npm install
        working-directory: cypress

      - name: Setup Cypress environment variables
        run: 'echo ''{
          "ENVIRONMENT": "TEST",
          "TEST": {
            "ENV": "1",
            "BASE_URL": "${{ env.TEST_BASE_URL }}"
            }
          }'' > cypress.env.json'
        working-directory: cypress

      - name: Run Cypress tests
        run: npx cypress run --browser chromium --spec "cypress/integration/Autentication/Login.ts"
        working-directory: cypress
